/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandelbrots;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.MemoryImageSource;

/**
 *
 * @author rbarzdins
 */
public class Mandelbrots extends javax.swing.JDialog {

    double z;
    int presedX1;
    int presedX2;
   
    
    
    /**
     * Creates new form mandelbrots
     */
    public Mandelbrots(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aNoText = new javax.swing.JTextField();
        bNoText = new javax.swing.JTextField();
        bLidzText = new javax.swing.JTextField();
        aLidzText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AprMandel = new javax.swing.JButton();
        Panelis = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNoTextActionPerformed(evt);
            }
        });

        bNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoTextActionPerformed(evt);
            }
        });

        bLidzText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLidzTextActionPerformed(evt);
            }
        });

        aLidzText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLidzTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Līdz");

        jLabel2.setText("A");

        jLabel3.setText("B");

        jLabel4.setText("No");

        AprMandel.setText("Mandelbrots");
        AprMandel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprMandelActionPerformed(evt);
            }
        });

        Panelis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelisMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelisLayout = new javax.swing.GroupLayout(Panelis);
        Panelis.setLayout(PanelisLayout);
        PanelisLayout.setHorizontalGroup(
            PanelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelisLayout.setVerticalGroup(
            PanelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Panelis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aLidzText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLidzText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AprMandel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aLidzText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLidzText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Panelis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(AprMandel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aNoTextActionPerformed

    private void bNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNoTextActionPerformed

    private void bLidzTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLidzTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLidzTextActionPerformed

    private void aLidzTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLidzTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aLidzTextActionPerformed

    public void zime(){
    double aNo = Double.parseDouble(aNoText.getText());
    double bNo = Double.parseDouble(bNoText.getText());
    double aLidz = Double.parseDouble(aLidzText.getText());
    double bLidz = Double.parseDouble(bLidzText.getText());
    int augstums = Panelis.getHeight();
    int platums = Panelis.getWidth();
    int j=0;
    int pixels[] = new int[platums*augstums];
    double aJaun;
    double bJaun;
    Image image;
    image = createImage(new MemoryImageSource(platums,augstums,pixels,0,platums));
    Graphics g=Panelis.getGraphics();
        int m = 10;
        for (int y = 0; y < augstums; y++) {
            double b = bNo + (y*((bLidz-bNo)/augstums));
            for (int x = 0; x < platums; x++) {
                
                double a = aNo + (x*((aLidz-aNo)/platums));

                double bVec = b;
                double aVec = a;
                double cReals = a;
                double cImag = b;
               
                
                int i = 0;
                
                do {
                    aJaun = (Math.pow(aVec,2)) - (Math.pow(bVec,2))+cReals;
                    bJaun = 2*aVec*bVec + cImag;
                    z = Math.abs((Math.pow(aJaun,2)) + (Math.pow(bJaun,2)));
                    aVec = aJaun;
                    bVec = bJaun;
                    i++;     
                } while (i<100 && z<=m);
                    
            
                
                if (i>=100) {
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|0;
                } else if(i>10 && i<=20) {
                    pixels[j] = (255<<24)|(0<<16)|(255<<8)|30;
                } else if (i>20 && i<=30){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|60;
                }else if (i>30 && i<=40){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|90;
                }else if (i>40 && i<=50){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|120;
                }else if (i>50 && i<=60){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|150;
                }else if (i>60 && i<=70){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|180;
                }else if (i>70 && i<=80){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|210;
                }else if (i>80 && i<=90){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|235;
                }else if (i>90 && i<=99){
                    pixels[j] = (255<<24)|(0<<16)|(0<<8)|255;
                } else if(i>0 && i<=10){
                    pixels[j] = (255<<24)|(255<<16)|(0<<8)|255;
                }
                
                j++;
          
             
                //atliek punktu a;b
                
            }
        }
        
        g.drawImage(image,0,0,null);
    }
    private void AprMandelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprMandelActionPerformed

    zime();
    }//GEN-LAST:event_AprMandelActionPerformed


    
    
    private void PanelisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelisMousePressed
        presedX1 = 0;
        presedX2 = 0;
        presedX1 = evt.getX();
    }//GEN-LAST:event_PanelisMousePressed

    private void PanelisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelisMouseReleased
        
        presedX2 = evt.getX();
        System.out.println(presedX1+ " "+presedX2);
    }//GEN-LAST:event_PanelisMouseReleased

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mandelbrots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mandelbrots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mandelbrots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mandelbrots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mandelbrots dialog = new Mandelbrots(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AprMandel;
    private javax.swing.JPanel Panelis;
    private javax.swing.JTextField aLidzText;
    private javax.swing.JTextField aNoText;
    private javax.swing.JTextField bLidzText;
    private javax.swing.JTextField bNoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
